routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => ['auth']], function () {

    Route::get('/home', 'DasarPhpController@index')->name('home');
    Route::get('/bagian/1/dasar/{nomor}', 'DasarPhpController@index')->name('dasar_1');
    Route::get('/add/papan_catur', 'DasarPhpController@html')->name('add_papan_catur');
    Route::get('/check', 'DasarPhpController@dasar3')->name('check');

    Route::resource('/company', 'CompanyController');
    Route::get('/source/company', 'CompanyController@source')->name('source.company');
    Route::get('/image/{id}', 'CompanyController@image')->name('image.company');
    Route::post('/image/upload', 'CompanyController@image_store')->name('image.upload');
    Route::get('/image/destroy', 'CompanyController@image_destroy')->name('image.destroy');

    Route::resource('/employe', 'EmployeController');
    Route::get('/source/employe', 'EmployeController@source')->name('source.employe');


    Route::resource('/buku', 'BukuController');
    Route::get('/source/buku', 'BukuController@source')->name('source.buku');

    Route::resource('/transaksi', 'TransaksiController');
    Route::get('/source/transaksi', 'TransaksiController@source')->name('source.transaksi');

});

app/Transaksi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Transaksi extends Model
{
    protected $fillable = ['kode_transaksi', 'buku_id','create_id','nama_pembeli','tgl_transaksi','harga','jumlah'];

    protected $primaryKey = 'id_btransaksi ';

    public function buku()
    {
        return $this->belongsTo(Buku::class,'buku_id');
    }
    public function user()
    {
        return $this->belongsTo(User::class,'create_id');
    }

}

app/Http/Controllers/TransaksiController.php
<?php

namespace App\Http\Controllers;

use App\Transaksi;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;
use Auth;

class TransaksiController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('transaksi.table');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $buku = Transaksi::all();
        return view('transaksi.form',compact('buku'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = Transaksi::create($request->all());
        return $data;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $show = true;
        $data = Transaksi::find($id);
        return view('transaksi.form',compact('data','show'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Transaksi::find($id);
        $update=  "update(".$id.")";
        return view('transaksi.update',compact('data','update'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(request $request, $id)
    {
        $update = Transaksi::where('id_buku',$id)->update($request->all());
        return $update;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $destroy = Transaksi::destroy($id);
        return  $destroy;
    }

    public function source()
    {        
        $query = Transaksi::query()->latest('updated_at');
  
        return DataTables::eloquent($query)      
        ->addIndexColumn()
        ->addColumn('buku', function ($row) {             
            return $row->buku->name;
        })
        ->addColumn('create', function ($row) {             
            return $row->user->name;
        })
        ->addColumn('action', function($row){
            $show =  'show("'.$row->id_transaksi.'")';
            $edit =  'edit('.$row->id_transaksi.')';
            $hapus =  'hapus('.$row->id_transaksi.')';
            $btn = "<div class='btn-group'>
                        <button type='button' onclick = ". $show." class='btn bg-gradient-info' data-toggle='modal' data-target='#modal-default'>
                            <i class='fa fa-eye'></i>
                        </button>                    
                        <button type='button' onclick = ". $edit." class='btn bg-gradient-warning' data-toggle='modal' data-target='#modal-default'>
                            <i class='fa fa-pencil-alt'></i>
                        </button>
                        
                        <button type='button' class='btn bg-gradient-danger' onclick = ". $hapus.">
                            <i class='fa fa-trash-alt'></i>
                        </button>
                    </div>";
            return $btn;
        })
        ->rawColumns(['action'])
        ->toJson();
    }
}

resources/views/transaksi/form.blade.php
<form id="form_create">
    <div class="modal-body" id="modal_form">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Kode Buku</label>
                    <input type="text" {{ !empty($show) ? 'readonly' : '' }} value="{{ !empty($show) ? $data->kode_buku : '' }}" name="kode_buku" id="kode_buku" class="form-control">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Nama</label>
                    <input type="email" {{!empty($show) ? 'readonly' : '' }} value="{{ !empty($show) ? $data->name : '' }}" name="name" placeholder="example@gmail.com" id="name" class="form-control">
                </div>
            </div>    
        </div>
    </div>
@if (empty($show))
    <div class="modal-footer justify-content-between">
        <button id="submit" onclick="store()" type="button" class="btn btn-primary">Save</button>
    </div>
@endif
    
</form>

@push('script')
<script>
    $('#logo').change(function(){
           
           let reader = new FileReader();
       
           reader.onload = (e) => { 
       
             $('#image_preview_container').attr('src', e.target.result); 
           }
       console.log(reader.readAsDataURL(this.files[0]));
           reader.readAsDataURL(this.files[0]); 
         
          });
</script>
    
@endpush

resources/views/transaksi/table.blade.php
@extends('layouts.admin')

@section('title')
Transaksi
@endsection

@section('part')
Transaksi
@endsection
@push('css')
<link rel="stylesheet" href="{{ asset('assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{ asset('assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
@endpush

@section('content')
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Transaksi Data</h3>
    <button style="float:right" type='button' onclick='create()' class='btn btn-success' data-toggle='modal'
      data-target='#modal-default'>
      <i class='fa fa-plus'></i>
    </button>
  </div>
  <!-- /.card-header -->
  <div class="card-body">
    <table id="table_transaksi" class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>No</th>
          <th>Kode Transaksi</th>
          <th>Buku</th>
          <th>Nama Pembeli</th>
          <th>Tanggal Transaksi</th>
          <th>Harga</th>
          <th>Jumlah</th>
          {{-- <th>Cabang</th> --}}
          <th>Create By</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>

    </table>
  </div>
  <!-- /.card-body -->

  {{-- modal --}}
  <div class="modal fade" id="modal-default">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Form Create</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <i style="display:none;" id="loading" class="fas fa-sync-alt fa-spin"></i>

            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div id="modal_form"></div>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div>

</div>
@endsection

@push('js')
<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{ asset('assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{ asset('assets/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{ asset('assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
@endpush

@push('script')
<script>
  const $table = $("#table_transaksi").DataTable({
        autoWidth: false,
        processing: true,
        serverSide: true,
        responsive: true,
        ajax: {
            url : '{!! route("source.transaksi") !!}',
            dataSrc: 'data'
        },
        language: {
            paginate: {
                previous: "<i class='fa fa-chevron-left'></i>",
                next: "<i class='fa fa-chevron-right'></i>",
            }
        },
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex' , orderable: false, searchable: false},
            {data: 'kode_transaksi', name: 'kode_transaksi'},
            {data: 'buku', name: 'buku'},
            {data: 'nama_pembeli', name: 'nama_pembeli'},
            {data: 'tgl_transaksi', name: 'tgl_transaksi'},
            {data: 'harga', name: 'harga'},
            {data: 'jumlah', name: 'jumlah'},
            {data: 'create', name: 'create'},
            {data: 'action', name: 'action', searchable : false, orderable : false,className: 'text-center'}
        ],
        search: {
            "regex": true
        }
    });
    function create()
  {
    
      $.ajax({
          url: "{{route('transaksi.create')}}",
          cache: false,
          beforeSend: function() {   
              $('.modal-title').text('');
              $( "#form_create" ).remove();
              $( "#form_update" ).remove();            
              $( "#modal-default" ).show();            
              $( "#loading" ).show();
              $('.modal-title').text('Form Create');
          },
          success: function(html){
              $( "#loading" ).hide();                
              $( "#modal_form" ).append(html); 
              $table.ajax.reload()              
          }
      });

  }

  function edit(val)
  {
      $.ajax({
          url: window.location.origin+window.location.pathname+'/'+val+'/edit',
        //   data: {'id':val},          
          cache: false,
          beforeSend: function() {   
              $('.modal-title').text('');
              $( "#form_update" ).remove();
              $( "#form_create" ).remove();  
              $( "#modal-default" ).show();            
              $( "#loading" ).show();
              $('.modal-title').text('Form Update');
          },
          success: function(data){
              $( "#loading" ).hide();                
              $( "#modal_form" ).append(data);               
          }
      });
  }

  function show(val)
  {
      $.ajax({
          type: 'GET',
          url: window.location.origin+window.location.pathname+'/'+val,
        //   data: {'id':val},          
          cache: false,
          beforeSend: function() {   
              $('.modal-title').text('');
              $( "#form_update" ).remove();
              $( "#form_create" ).remove();  
              $( "#modal-default" ).show();            
              $( "#loading" ).show();
              $('.modal-title').text('Form Show');
          },
          success: function(data){
              $( "#loading" ).hide();                
              $( "#modal_form" ).append(data);               
          }
      });
  }

  function hapus(val)
  {
      $.ajax({
          type: 'DELETE',
          headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
          url: window.location.origin+window.location.pathname+'/'+val,
          data: {'id':val},          
          cache: false,
          beforeSend: function() {   
             
          },
          success: function(data){
            $table.ajax.reload()               
          }
      });
  }

  function update(val)
  {
    var data = $('#form_update').serialize();

    $.ajax({
        type: 'put',
        headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
        url: window.location.origin+window.location.pathname+"/"+val,
        data: data,
        beforeSend: function (data) {
            console.log(data)
            $('#submit').prop('disabled',true);
        },
        success: function (data) {
          $('#modal-default').modal('toggle');
          $table.ajax.reload()
        },
        error :function( data ) {
          $('#submit').prop('disabled',false);
          if( data.status === 422 ) {
            var errors = $.parseJSON(data.responseText);
            $.each(errors['errors'], function( index, value ) {             
              $('#form_update').Toasts('create', {                 
                title: 'Error Input'+index,
                autohide: true,
                class: 'bg-danger',
                delay: 2500,
                body: value
          
              })
            });
            
          }
        },
    });
  }


  function store()
  {
    var data = $('#form_create').serialize();
    $.ajax({
        type: 'post',
        headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
        url: window.location.origin+window.location.pathname,        
        dataType:'json',
        data: data, 
        async: true,
        beforeSend: function () {
            $('#submit').prop('disabled',true);
        },
        success: function (data) {
          $('#modal-default').modal('toggle');
          $table.ajax.reload()
        },
        error :function( data ) {
          $('#submit').prop('disabled',false);
          if( data.status === 422 ) {
            var errors = $.parseJSON(data.responseText);
            $.each(errors['errors'], function( index, value ) {             
              $('#form_create').Toasts('create', {                 
                title: 'Error Input'+index,
                autohide: true,
                class: 'bg-danger',
                delay: 2500,
                body: value
          
              })
            });
            
          }
        },
    });
  }

 
</script>
@endpush

resources/views/transaksi/update.blade.php
<form method="post" enctype="multipart/form-data" id="form_update">
    <div class="modal-body">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="">Kode buku</label>
                <input type="text"value="{{ !empty($data->kode_buku) ? $data->kode_buku : '' }}" name="kode_buku" id="kode_buku" class="form-control">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="">Nama</label>
                <input type="email" {{!empty($show) ? 'readonly' : '' }} value="{{ !empty($data->name) ? $data->name : '' }}" name="name" id="name" class="form-control">
            </div>
        </div>    

    </div>
</div>

<div class="modal-footer justify-content-between">
    <button id="submit" type="submit" onclick="{{$update}}" class="btn btn-primary">Update</button>
</div>
</form>