routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => ['auth']], function () {

    Route::get('/home', 'DasarPhpController@index')->name('home');
    Route::get('/bagian/1/dasar/{nomor}', 'DasarPhpController@index')->name('dasar_1');
    Route::get('/add/papan_catur', 'DasarPhpController@html')->name('add_papan_catur');
    Route::get('/check', 'DasarPhpController@dasar3')->name('check');

    Route::resource('/company', 'CompanyController');
    Route::get('/source/company', 'CompanyController@source')->name('source.company');
    Route::get('/image/{id}', 'CompanyController@image')->name('image.company');
    Route::post('/image/upload', 'CompanyController@image_store')->name('image.upload');
    Route::get('/image/destroy', 'CompanyController@image_destroy')->name('image.destroy');

    Route::resource('/employe', 'EmployeController');
    Route::get('/source/employe', 'EmployeController@source')->name('source.employe');


    Route::resource('/buku', 'BukuController');
    Route::get('/source/buku', 'BukuController@source')->name('source.buku');

    Route::resource('/transaksi', 'TransaksiController');
    Route::get('/source/transaksi', 'TransaksiController@source')->name('source.transaksi');

});

resources/views/parts/_css.blade.php
<link rel="stylesheet" href="{{ asset('assets/plugins/fontawesome-free/css/all.min.css') }}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Tempusdominus Bbootstrap 4 -->
<link rel="stylesheet" href="{{ asset('assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
<!-- iCheck -->
<link rel="stylesheet" href="{{ asset('assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
<!-- JQVMap -->
<link rel="stylesheet" href="{{ asset('assets/plugins/jqvmap/jqvmap.min.css') }}">
<!-- Theme style -->
<link rel="stylesheet" href="{{ asset('assets/dist/css/adminlte.min.css') }}">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="{{ asset('assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css') }}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{{ asset('assets/plugins/daterangepicker/daterangepicker.css') }}">
<!-- summernote -->
<link rel="stylesheet" href="{{ asset('assets/plugins/summernote/summernote-bs4.css') }}">
<!-- Google Font: Source Sans Pro -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

@stack('css')

@stack('style')

resources/views/parts/_js.blade.php
<script src="{{ asset('assets/plugins/jquery/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('assets/plugins/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{ asset('assets/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- ChartJS -->
<script src="{{ asset('assets/plugins/chart.js/Chart.min.js') }}"></script>
<!-- Sparkline -->
<script src="{{ asset('assets/plugins/sparklines/sparkline.js') }}"></script>
<!-- JQVMap -->
<script src="{{ asset('assets/plugins/jqvmap/jquery.vmap.min.js') }}"></script>
<script src="{{ asset('assets/plugins/jqvmap/maps/jquery.vmap.usa.js') }}"></script>
<!-- jQuery Knob Chart -->
<script src="{{ asset('assets/plugins/jquery-knob/jquery.knob.min.js') }}"></script>
<!-- daterangepicker -->
<script src="{{ asset('assets/plugins/moment/moment.min.js') }}"></script>
<script src="{{ asset('assets/plugins/daterangepicker/daterangepicker.js') }}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('assets/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
<!-- Summernote -->
<script src="{{ asset('assets/plugins/summernote/summernote-bs4.min.js') }}"></script>
<!-- overlayScrollbars -->
<script src="{{ asset('assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}"></script>
<script src="{{ asset('assets/dist/js/adminlte.js')}}"></script>

@stack('js')

@stack('script')

resources/views/parts/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.0.4
    </div>
  </footer>

resources/views/parts/header.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
  </ul>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Messages Dropdown Menu -->
    <li class="nav-item dropdown">
      <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
        {{ Auth::user()->name }} <span class="caret"></span>
    </a>

    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{{ route('logout') }}"
           onclick="event.preventDefault();
                         document.getElementById('logout-form').submit();">
            {{ __('Logout') }}
        </a>

        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
    </li>
  </ul>

</nav>
<!-- /.navbar -->

resources/views/parts/side.blade.php
 <!-- Main Sidebar Container -->
 <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link logo-switch">
      {{-- <img src="{{ asset('assets/dist/img/Logo_Transisi.png')}}" class="brand-image-xs logo-xl" 
        style=" width: 50%;
                background-color: white;
                left: 24%;"
      > --}}
    </a>

    <!-- Sidebar -->
    <div class="sidebar">


      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->

          {{-- <li class="nav-header">PHP DASAR</li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-circle"></i>
              <p>
                Bagian 1
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{route('dasar_1','1')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Dasar 1</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{route('dasar_1','2')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Dasar 2</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{route('dasar_1','3')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Dasar 3</p>
                </a>
              </li>
            </ul>
          </li>


          <li class="nav-header">LARAVEL DASAR</li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-circle"></i>
              <p>
                Bagian 2
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item has-treeview">
                <a href="{{route('company.index')}}" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>
                      COMPANY
                    </p>
                  </a>
                </li>
                <li class="nav-item has-treeview">
                  <a href="{{route('employe.index')}}" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>
                      EMPLOYE
                    </p>
                  </a>
                </li>
            </ul>
          </li> --}}
          
          <li class="nav-header">Master</li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-circle"></i>
              <p>
                Master Data  
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item has-treeview">
                <a href="{{route('buku.index')}}" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>
                      Buku
                    </p>
                  </a>
                </li>
                <li class="nav-item has-treeview">
                  <a href="{{route('transaksi.index')}}" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>
                      Transaksi
                    </p>
                  </a>
                </li>
                <li class="nav-item has-treeview">
                  <a href="{{route('company.index')}}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>
                        Cabang
                      </p>
                    </a>
                  </li>
                  <li class="nav-item has-treeview">
                    <a href="{{route('employe.index')}}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>
                        User
                      </p>
                    </a>
                  </li>
            </ul>
          </li>
          
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>